[package]
name = "organism"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
rand.workspace = true
nora_neat.workspace = true
uuid.workspace = true
ev_core.workspace = true
bus.workspace = true
strum.workspace = true
